services:
  postgres:
    image: postgres:16
    container_name: nutrition_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nutrition_network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: nutrition_zookeeper
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - nutrition_network

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: nutrition_kafka
    restart: always
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_LOG4J_ROOT_LOGLEVEL: ERROR
    depends_on:
      - zookeeper
    networks:
      - nutrition_network

  food_detector:
    build:
      context: ./food_detection
    container_name: nutrition_food_detector
    restart: always
    volumes:
      - ./food_detection/best.pt:/app/best.pt
    depends_on:
      - kafka
    networks:
      - nutrition_network
    command:
      - --weights
      - /app/best.pt
      - --bootstrap
      - kafka:29092
      - --input-topic
      - food_images
      - --output-topic
      - food_cls
      - --group-id
      - food-detector

  backend: 
    build:
      context: .
    container_name: nutrition_backend
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - postgres
      - kafka
    networks:
      - nutrition_network

volumes:
  postgres_data:

networks:
  nutrition_network:
    driver: bridge